---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    # Raise pull requests for version updates
    # to github-actions against the `main` branch
    target-branch: "main"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    # Raise pull requests for version updates
    # to github-actions against the `main` branch
    target-branch: "main"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    # Raise pull requests for version updates
    # to github-actions against the `main` branch
    target-branch: "main"
    ignore:
      - dependency-name: "homeassistant"
