force_recovery:
  name: Force recovery
  description: Force an immediate connection check and recovery attempt.
  fields:
    entity_id:
      name: Fan entity
      description: Optional. Limit the recovery attempt to a single SmartCocoon fan.
      required: false
      selector:
        entity:
          domain: fan
          integration: smartcocoon

get_device_status:
  name: Get device status
  description: Log current connection/recovery status for SmartCocoon fans.
  fields:
    entity_id:
      name: Fan entity
      description: Optional. Get status for a single SmartCocoon fan.
      required: false
      selector:
        entity:
          domain: fan
          integration: smartcocoon
# Describes the format for available fan services

set_eco_mode:
  name: Set eco mode
  description: Set the fan to eco mode.
  target:
    entity:
      integration: smartcocoon
      domain: fan
  fields:
    eco_mode:
      name: Eco mode
      description: Eco mode status
      required: true
      selector:
        boolean:

set_auto_mode:
  name: Set auto mode
  description: Set the fan to auto mode.
  target:
    entity:
      integration: smartcocoon
      domain: fan
  fields:
    eco_mode:
      name: Auto mode
      description: Auto mode status
      required: true
      selector:
        boolean:

set_speed:
  name: Set speed
  description: Set the exact speed of the fan.
  target:
    entity:
      integration: smartcocoon
      domain: fan
  fields:
    smartcocoon_speed:
      name: Speed
      description: Speed
      required: true
      selector:
        number:
          min: 1
          max: 100
