---
name: Manage labels

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          skip-delete: true

  auto-label:
    name: Auto-label PRs
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Auto-label PR
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
        with:
          configuration-path: ".github/labeler-config.yml"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
