---
name: Draft a release note
on:
  push:
    branches:
      - main
      - develop
jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
