---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.13.2"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5.0.0
      - name: Set up Python 3.13.3
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.13.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -e .
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --color=always

  test:
    runs-on: "ubuntu-latest"
    name: Test Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.13.2", "3.13.3", "3.13.4"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5.0.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -e .
      - name: Run tests with coverage
        run: |
          pytest --cov=custom_components.smartcocoon --cov-report=xml --cov-report=html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-python-${{ matrix.python-version }}
          fail_ci_if_error: false

  python-compatibility:
    runs-on: "ubuntu-latest"
    name: Python Compatibility Check
    strategy:
      matrix:
        python-version: ["3.13.1", "3.13.2"]
        should-fail: [true, false]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5.0.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Python version compatibility
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.should-fail }}" = "true" ]; then
            # This should fail for Python < 3.13.2
            if pip install -r requirements.txt; then
              echo "ERROR: Installation should have failed for Python ${{ matrix.python-version }}"
              exit 1
            else
              echo "SUCCESS: Installation correctly failed for Python ${{ matrix.python-version }}"
            fi
          else
            # This should succeed for Python >= 3.13.2
            pip install -r requirements.txt
            echo "SUCCESS: Installation succeeded for Python ${{ matrix.python-version }}"
          fi

  security:
    runs-on: "ubuntu-latest"
    name: Security Scan
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5.0.0
      - name: Set up Python 3.13.3
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.13.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -e .
      - name: Run safety vulnerability scan
        run: |
          echo "🔍 Running safety vulnerability scan..."
          # Note: safety now requires authentication for scan command
          # For CI, we'll use pip-audit which provides similar functionality
          echo "Skipping safety scan (requires authentication)"
      - name: Run pip-audit dependency audit
        run: |
          echo "🔍 Running pip-audit dependency audit..."
          pip-audit --requirement requirements.txt --requirement requirements_test.txt --desc --format=json
      - name: Run semgrep security analysis
        run: |
          echo "🔍 Running semgrep security analysis..."
          semgrep --config=auto --error --json --output=semgrep-results.json .
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan-results
          path: |
            semgrep-results.json
          retention-days: 30

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v5.0.0"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v5.0.0"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
